name: Strapi_Fargate

on:
  push:
    branches: developer

jobs:
    Strapi_task:
        runs-on: ubuntu-latest

        env:
            IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/strapi3

        steps:
        - name: Checkout-code
          uses: actions/checkout@v4

        - name: docker login
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Creating env file
          run: |
            cat <<EOF > ./strapi10/.env
            ${{secrets.ENV_FILE}}
            EOF
        
        - name: Build image
          run: |
            docker build -t ${{env.IMAGE_NAME}}:v5 ./strapi10/

        - name: Push the image to docker hub
          run: |
            docker push ${{env.IMAGE_NAME}}:v5 

        - name: terraform setup
          uses: hashicorp/setup-terraform@v3

        - name: Terraform init
          run: terraform init
          working-directory: ./terraform

        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: ./terraform
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Import terrfrom.tfstate file as artifact
          uses: actions/upload-artifact@v4
          with:
            name: location of terraform file
            path: ./terraform/terraform.tfstate
        