name: Strapi_Fargate

on:
  push:
    branches: master

jobs:
    Strapi_task:
        runs-on: ubuntu-latest

        env:
            IMAGE_TAG: v${{ github.run_number }}
            IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/strapi3

        steps:
        - name: Checkout-code
          uses: actions/checkout@v4

        - name: docker login
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Creating env file
          run: |
            cat <<EOF > ./strapi10/env
            ${{secrets.ENV_FILE}}
            EOF

            cp ./strapi10/env ./strapi10/.env

        - name: list
          run: |
            ls -al
            ls -al ./strapi10
            ls -al ./strapi10/.env
            cat env
        
        # - name: Build image
        #   run: |
        #     docker build -t ${{env.IMAGE_NAME}}:v1 ./strapi10/

        # - name: Push the image
        #   run: |
        #     docker push ${{env.IMAGE_NAME}}:v1 

        - name: Upload .env as artifact
          uses: actions/upload-artifact@v4
          with:
             include-hidden-files: true
             name: env-file
             path: ./strapi10
        