name: Strapi_Fargate

on:
  push:
    branches: master

jobs:
    Strapi_task:
        runs-on: ubuntu-latest

        env:
            IMAGE_TAG: v${{ github.run_number }}
            IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/strapi3

        steps:
        - name: Checkout-code
          uses: actions/checkout@v4

        - name: docker login
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Creating env file
          run: |
            printf "%s" "${{secrets.ENV_FILE}}" > ./strapi10/.env
        
        - name: Build image
          run: |
            docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} ./strapi10/

        - name: Push the image
          run: |
            docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} 

        - name: Upload .env as artifact
          uses: actions/upload-artifact@v4
          with:
             name: env-file
             path: ./strapi10/.env
        